services:
  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - NEXT_PUBLIC_DEEPAR_LICENSE_KEY=${NEXT_PUBLIC_DEEPAR_LICENSE_KEY}
        - NEXT_PUBLIC_TURN_SERVER=${NEXT_PUBLIC_TURN_SERVER}
        - NEXT_PUBLIC_TURN_USERNAME=${NEXT_PUBLIC_TURN_USERNAME}
        - NEXT_PUBLIC_TURN_PASSWORD=${NEXT_PUBLIC_TURN_PASSWORD}
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.live-app.rule=Host(`contenidovaleria.shop`)"
      - "traefik.http.routers.live-app.entrypoints=websecure"
      - "traefik.http.routers.live-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.live-app.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    networks:
      - proxy

networks:
  proxy:
    external: true
